---
language: python
services: docker
env:
  global:
    - namespace="caseraw"
    - role_name="ansible_role_chrony"
  matrix:
    - image="ansible-molecule-centos" tag="7"
    - image="ansible-molecule-centos" tag="8"
    - image="ansible-molecule-centos" tag="latest"
    - image="ansible-molecule-fedora" tag="28"
    - image="ansible-molecule-fedora" tag="29"
    - image="ansible-molecule-fedora" tag="30"
    - image="ansible-molecule-fedora" tag="31"
    - image="ansible-molecule-fedora" tag="latest"
cache: pip
install:
  - pip install --upgrade pip setuptools
  - pip install molecule docker
script:
  - python --version
  - ansible --version
  - molecule --version
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

...
