---
language: python
python:
  - "3.7"
services:
  - docker
install:
  - pip install --upgrade pip setuptools
  - pip install molecule docker
script:
  - python --version
  - ansible --version
  - molecule --version
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

...
