---
- name: Unarm ntp - Check if ntpd is installed - part 1
  package_facts:
    manager: auto

- name: Unarm ntp - Ensure ntpd is stopped and disabled - part 2
  systemd:
    name: ntpd
    state: stopped
    enabled: False
    daemon_reload: True
  when: "'ntp' in ansible_facts.packages"

- name: Unarm ntp - Ensure ntpd is masked - part 3
  systemd:
    name: ntpd
    masked: True
  when: "'ntp' in ansible_facts.packages"

- name: Ensure chrony is installed
  package:
    name: '{{ role_chrony_required_packages }}'
    state: present
  notify: start_restart_chronyd

- name: Deploy chrony configuration file
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'
  notify: start_restart_chronyd

- name: Ensure chrony service is enabled and running - part 1
  service_facts:

- name: Ensure chrony service is enabled and running - part 2
  debug:
    msg: "Service 'chronyd' is not running or enabled"
  when: (ansible_facts.services["chronyd.service"].state == "stopped") or
        (ansible_facts.services["chronyd.service"].state == "unknown") or
        (ansible_facts.services["chronyd.service"].status == "disabled")
  changed_when: True
  notify: start_restart_chronyd

- name: Ensure timezone is set to {{ role_chrony_time_zone }}
  timezone:
    name: '{{ role_chrony_time_zone }}'

...
