---
- name: Ensure ntpd is unarmed (will fail if ntpd service is absent)
  systemd:
    name: ntpd
    state: stopped
    enabled: False
    masked: True
  ignore_errors: True

- name: Ensure chrony is installed
  yum:
    name: '{{ role_chrony_required_packages }}'
    state: present
  notify: start_chrony

- name: Deploy chrony configuration file
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart_chrony

- name: Ensure timezone is set to {{ role_chrony_time_zone }}
  timezone:
    name: '{{ role_chrony_time_zone }}'

...
