---
- name: Ensure chrony is started
  service:
    name: chronyd
    state: stared
  listen: start_chrony

- name: Ensure chrony is restarted
  service:
    name: chronyd
    state: restarted
  listen: restart_chrony

...
