---
- name: Ensure chrony is started/restarted and enabled
  service:
    name: chronyd
    state: restarted
    enabled: True
    masked: False
    daemon_reload: True
  listen: start_restart_chronyd

...
