---
dependency:
  name: galaxy
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: playbook.yml
scenario:
  name: default
lint:
  name: yamllint
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: nsible_role_chrony-ansible-molecule-centos-7
    box: centos/7
    imemory: 1024
    cpus: 1
verifier:
  name: ansible
  lint:
    name: ansible-lint

...
