---
dependency:
  name: galaxy
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: playbook.yml
scenario:
  name: default
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: "${role_name:-ansible_role_chrony}-${image:-ansible-molecule-centos}-${tag:-latest}"
    image: "${namespace:-caseraw}/${image:-ansible-molecule-centos}:${tag:-latest}"
    command: /usr/sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: True
    pre_build_image: True
verifier:
  name: ansible
  lint:
    name: ansible-lint

...
