---
dependency:
  name: galaxy
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
  lint:
    name: ansible-lint
  playbooks:
    converge: playbook.yml
scenario:
  name: default
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: chrony-test-centos-7
    image: caseraw/ansible-molecule-centos:7
    command: /usr/sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: True
    pre_build_image: True
verifier:
  name: ansible
  lint:
    name: ansible-lint

...