---
dependency:
  name: galaxy
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
      stdout_callback: yaml
      bin_ansible_callbacks: True
  lint:
    name: ansible-lint
  playbooks:
    converge: playbook.yml
scenario:
  name: default
lint:
  name: yamllint
  options:
    config-file: molecule/default/yamllint.yml
driver:
  name: docker
platforms:
  - name: "${role_name:-ansible_role_chrony}-${image:-ansible-molecule-centos}-${tag:-7}"
    image: "${namespace:-caseraw}/${image:-ansible-molecule-centos}:${tag:-7}"
    command: "${cmd:-/usr/sbin/init}"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: True
    pre_build_image: True
verifier:
  name: ansible
  lint:
    name: ansible-lint

...
